### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Youras** [eyal0/OctoPrint-TimeToFilament#41]
Hello, 

my octopi has no intenet connection, thus I install all the plugins via the webapplication with uploading the zip folder.
However, this plugin seems to require internet connection, since I get some HTTP request error 

`
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /eyal0/OctoPrint-PrintTimeGenius/archive/master.zip (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xb547d808>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Can this be resolved somehow?

Best,
Raschid

**Comment by eyal0** [comment]
The PrintTimeGenius plugin is required for the TimeToFilament plugin to work. Do you have PTG installed?

**Comment by Youras** [comment]
Yes, I successfully installed the PTG plugin a couple of weeks ago.

**Comment by eyal0** [comment]
Okay, I have an idea.  Let's try to remove the OctoPrint-PrintTimeGenius requirement check from TimeToFilament.  You already have PTG installed so it should be fine.

Unzip the zipfile that you are installed.  In the file `setup.py` on line 36 we see this: https://github.com/eyal0/OctoPrint-TimeToFilament/blob/master/setup.py#L36

```python
plugin_requires = ["OctoPrint-PrintTimeGenius @ https://github.com/eyal0/OctoPrint-PrintTimeGenius/archive/master.zip",
```

Let's remove the github part so that it won't go to the internet to look for the latest version:

```python
plugin_requires = ["OctoPrint-PrintTimeGenius",
```

After modification, rezip that file and try installation again.

If that doesn't work then let's remove the PTG requirement check entirely.  This isn't as good because it will now register TTF without needing PTG and you won't get a warning if you try to remove PTG without first removing TTF.

```python
plugin_requires = [
```

Like that.  In both cases, we are only removing the requirement **check**.  The requirement continues to exist, however.  TimeToFilament will not work properly without PTG installed.

Let me what worked so that I can give this advice again as needed.  Let me know if you need help with the zip files.

**Comment by Youras** [comment]
Your first advice did the job, thank you!
